on: 
  workflow_dispatch:
    
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.KEY }}"

      - name: Sync
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ./sync.sh
      - name: Hello world action step
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        id: hello
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
